### ISSUE TITLE
Parses http:abc/ differently from WHATWG URL parser

### ISSUE THREAD

**Issue by TimothyGu** [alwinb/spec-url#3]
With:

```js
// skeleton of the "parse-resolve-and-normalise" algorithm in the spec without a base URL
u = specUrl.parse("http:abc/");
u = specUrl.normalize(u);
u = specUrl.percentEncode(u);
console.log(specUrl.print(u));
```

spec-url gives `http:abc/`, which is not a resolved-URL. However, the WHATWG URL parser gives `http://abc/`, which _is_ a resolved-URL:

![image](https://user-images.githubusercontent.com/1538624/117528946-bae40300-afa2-11eb-98c8-0b714c5c07d3.png)

Discovered through the https://timothygu.me/urltester/ tool. `pathname` is computed with

```js
`${url.root || ""}${url.dirs ? url.dirs.join("/") + "/" : ""}${url.file || ""}`
```

**Comment by TimothyGu** [comment]
It appears that this is because we need to call `force`. This works as expected:

```js
u = specUrl.parse("http:abc/");
u = specUrl.force(u);
u = specUrl.normalize(u);
u = specUrl.percentEncode(u);
console.log(specUrl.print(u));
```

**Comment by alwinb** [comment]
Yes, the ‘force’, for lack of a better name, is a key part of the solution. This way, resolve is otherwise the same as in RFC (using what they call the non-strict merge).

**Comment by TimothyGu** [comment]
For the purpose of https://timothygu.me/urltester/, I ended up including two variants for spec-url: a normal variant without 'force' and an "absolute" variant that always calls 'force'. Of course, if a base is specified, then 'force' is always called by virtue of forceResolve. Does that sound reasonable to you?

**Comment by alwinb** [comment]
This URL tester looks great! This sounds good, but it does make me want to have a closer look at how the other libraries handle the corner cases. It should be interesting to see, and I hope my approach matches theirs.

**Comment by alwinb** [comment]
I've had another quick look at the test page. Quote:

> Since spec-url does not yet provide a high-level parsing function, we have to describe what exactly we do here

I have made a new release 1.2.0 which exposes a function WHATWGParseResolve (string, base-string). 
The API is low level on purpose, but if you have advice / ideas to make using it easier, please let me know. Such feedback is very helpful to me. 

Perhaps something else to note:

> The absolute variant is closer to how the WHATWG URL Standard operates, while the normal variant is closer to how Go's net/url operates.

I would say, the absolute (or forced) variant is designed to exactly match the behaviour of the WHATWG Standard. 
Or at least I wanted to state that here, because the goal of the project is **specifically** to prevent fragmentation and reconcile the WHATWG standard with the IETF RFCs. If there are differences in parsing, then that is a bug. 

One more thing, 

> root + (dirs &amp;&amp; (dirs.join(/) + /)) + file

The drive of file URLs get parsed as a separate component, which must be included in the pathname (with a '/' prefixed to it) as well. I'd like to expose a function for that but am still pondering some issues with percent coding around it, so that's for later.
